steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA',
        '.' # Build context is the current directory
      ]
    id: 'Build Image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'
      ]
    id: 'Push Image'
    waitFor: ['Build Image']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA',
        '--region=${_REGION}',
        '--platform=managed',
        '--allow-unauthenticated', # Or manage access via IAM
        '--port=3000'
        # '--set-env-vars=KEY=VALUE' # Add environment variables if needed
      ]
    id: 'Deploy to Cloud Run'
    waitFor: ['Push Image']

# Define images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'

# Define substitutions (you'll set these in the trigger)
substitutions:
  _SERVICE_NAME: 'health-app' # Default value, will be overridden by trigger
  _REGION: 'asia-south1'         # Default value
  _AR_REPO_NAME: 'health-app' # Default value for Artifact Registry repo
  # COMMIT_SHA is a built-in substitution

options:
  logging: CLOUD_LOGGING_ONLY
