import styles from './Footer.module.css'; // Import CSS module

export default function Footer() {
  return (
    // <footer className="bg-slate-900 text-slate-400 border-t border-slate-700">
    <footer className={styles.footer}>
      {/* <div className="container mx-auto max-w-6xl px-4 py-8 text-center"> */}
      <div className={styles.container}>
        {/* <div className="mb-6 p-4 bg-slate-800 rounded-lg border border-slate-700"> */}
        <div className={styles.disclaimerBox}>
          {/* <h4 className="font-semibold text-slate-300 mb-2"> */}
          <h4 className={styles.disclaimerTitle}>AI Generation Disclaimer</h4>
          {/* <p className="text-xs leading-relaxed"> */}
          <p className={styles.disclaimerText}>
            The information presented on this dashboard is generated by an AI model
            based on the uploaded document. It is for informational purposes only and should not
            be considered a substitute for professional medical advice, diagnosis, or treatment.
            Always seek the advice of your physician or other qualified health provider with
            any questions you may have regarding a medical condition.
          </p>
        </div>
        {/* <p className="text-sm text-slate-500"> */}
        <p className={styles.copyrightText}>
          &copy; {new Date().getFullYear()} Bodyclone HealthAI. All rights reserved.
        </p>
      </div>
    </footer>
  );
}
